Warning: untrusted X11 forwarding setup failed: xauth key data not generated
rsync: opendir "/hd1/scsnl/datafromlucas/100513_1_1.3T2" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1650) [generator=3.1.2]
Traceback (most recent call last):
  File "download_from_flywheel.py", line 292, in <module>
    num_unused = int(studies_rules[scanid_list[3]]['unused_num'])
KeyError: 'smp'
